# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "dev-sample-app"
client_id = "570821f4900172bee5b0090e800ded66"
application_url = "https://sip-vinyl-achievement-worldwide.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_payment_customizations"

[auth]
redirect_urls = [
  "https://sip-vinyl-achievement-worldwide.trycloudflare.com/auth/callback",
  "https://sip-vinyl-achievement-worldwide.trycloudflare.com/auth/shopify/callback",
  "https://sip-vinyl-achievement-worldwide.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "moh-dev-store-extensibility.myshopify.com"
